name: CI-CD

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-c:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build C test suite
        run: |
          mkdir build_test && cd build_test
          cmake ../tests/ctests -DCMAKE_BUILD_TYPE=Debug
          make -j$(nproc)

      - name: Run C tests
        run: ./build_test/bin/run_tests

  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install .[test]

      - name: Run tests
        run: pytest --cov --cov-report=xml tests	
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token:  ${{ secrets.CODECOV_TOKEN }}
          slug: INFN-MRI/pulserver		  
  
  docs:
    runs-on: ubuntu-20.04
    needs: [test-c, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          pip install .[doc]
          python -m pip install -r docs/requirements.txt
      
      - name: Build API documentation
        run: |
          python -m sphinx docs docs_build
      
      - name: Display structure of docs
        run: ls -R docs_build/	  
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_build
          destination_dir: .
          publish_branch: gh-pages
          keep_files: false
