"""Readout creation subroutine."""

__all__ = ['make_readout_lobe']

import logging

from types import SimpleNamespace

import numpy as np
import pypulseq as pp

from .._params import calc_kspace_readout_params


def log_and_raise(msg, exc=ValueError): # noqa
    logging.error(msg)
    raise exc(msg)


def make_readout_lobe(
    fov: float,
    npix: int,
    receiver_bandwidth: float,
    oversamp: float = 2.0,
    partial_fourier_factor: float = 1.0,
    rampsamp: bool = False,
    deadtime: float | tuple[float] = 0.0,
    system: pp.Opts | None = None,
    lstrip: bool = False,
    rstrip: bool = False,
) -> SimpleNamespace:
    """
    Design a Cartesian readout gradient lobe and aligned ADC event.

    This function generates a readout gradient (flat-top or ramp-sampled)
    together with a correctly aligned ADC. It supports oversampling, partial
    Fourier acquisition, optional dead times, and removal of gradient ramps
    for integration with crushers or rewinders.

    The ADC is aligned such that the center of k-space sampled by the ADC
    coincides with the center of the k-space trajectory generated by the
    gradient. Alignment accounts for ADC sampling at dwell midpoints,
    non-uniform k-space traversal during ramp sampling, and partial Fourier
    acquisition.

    Parameters
    ----------
    fov : float
        Field of view along the readout direction [m].
    npix : int
        Number of image pixels along the readout direction before oversampling
        and partial Fourier.
    receiver_bandwidth : float
        Target receiver bandwidth [Hz]. The achieved bandwidth may be slightly
        lower due to ADC raster alignment.
    oversamp : float, optional
        Readout oversampling factor. Default is 2.0.
    partial_fourier_factor : float, optional
        Fraction of k-space acquired along the readout direction
        (0 < partial_fourier_factor <= 1). Default is 1.0.
    rampsamp : bool, optional
        If True, perform ramp sampling (ADC spans ramps and flat).
        If False, ADC samples only the flat-top portion.
        Default is False.
    deadtime : float or tuple of float, optional
        Additional dead time [s] before and/or after the ADC window.
        If a scalar is provided, the same dead time is applied on both sides.
        If a tuple is provided, it specifies (pre, post) dead times.
        Default is 0.0.
    system : pp.Opts
        Pulseq system limits and raster settings.
    lstrip : bool, optional
        If True, remove the rising ramp of the gradient and shift the ADC delay
        accordingly. Default is False.
    rstrip : bool, optional
        If True, remove the falling ramp of the gradient. Default is False.

    Returns
    -------
    grad : pp.Gradient
        Readout gradient event.

    adc : pp.Adc
        ADC event aligned to the gradient k-space center.

    Notes
    -----
    For flat-top sampling, the k-space center lies at a linear time offset
    within the flat-top portion of the gradient:

    ``t_grad_center = grad.rise_time + pivot * grad.flat_time``

    For ramp sampling, the k-space center corresponds to the centroid of the
    gradient area:

    ``t_grad_center = pivot * grad.duration``

    In both cases, the ADC delay is chosen such that the ADC k-space center
    coincides with the gradient k-space center and is rounded to the ADC
    raster time.

    Examples
    --------
    Flat-top sampled readout (full Fourier):

    >>> grad, adc = make_readout_lobe(
    ...     fov=256e-3,
    ...     npix=256,
    ...     receiver_bandwidth=250e3, # 250 kHz -> 2 us dwell
    ...     oversamp=2.0,
    ...     system=sys,
    ... )

    Partial-echo flat-top readout:

    >>> grad, adc = make_readout_lobe(
    ...     fov=256e-3,
    ...     npix=256,
    ...     receiver_bandwidth=250e3, # 250 kHz -> 2 us dwell
    ...     partial_fourier_factor=0.75,
    ...     system=sys,
    ... )

    Flat-top readout stripped at the end for bridging with a crusher:

    >>> grad, adc = make_readout_lobe(
    ...     fov=256e-3,
    ...     npix=256,
    ...     receiver_bandwidth=250e3, # 250 kHz -> 2 us dwell
    ...     rstrip=True,
    ...     system=sys,
    ... )

    Ramp-sampled EPI readout with half-blip dead times:

    >>> grad, adc = make_readout_lobe(
    ...     fov=256e-3,
    ...     npix=256,
    ...     receiver_bandwidth=250e3, # 250 kHz -> 2 us dwell
    ...     rampsamp=True,
    ...     deadtime=0.5*blip_dur,
    ...     system=sys,
    ... )

    """
    if system is None:
        system = pp.Opts.default
    if np.isscalar(deadtime):
        deadtime = (deadtime, deadtime)

    # Compute readout parameters
    area, duration, num_samples = calc_kspace_readout_params(
        fov,
        npix,
        receiver_bandwidth,
        oversamp,
        partial_fourier_factor,
        system.adc_raster_time,
        system.grad_raster_time,
        system.adc_samples_divisor,
    )
    dwell_time = duration / num_samples

    # Compute gradient
    if rampsamp:
        extra_time = np.sum(deadtime).item()
        extra_area = (
            0.5 * system.max_slew * deadtime[0] ** 2
            + 0.5 * system.max_slew * deadtime[1] ** 2
        )
        grad = pp.make_trapezoid(
            area=area + extra_area,
            duration=duration + extra_time,
            system=system,
            max_grad=1.0 / (system.gamma * fov * dwell_time),
        )
        grad = pp.scale_grad(grad, area / grad.area, system)
    else:
        grad = pp.make_trapezoid(
            flat_area=area,
            flat_time=duration,
            system=system,
        )
        if deadtime[0] > grad.rise_time:
            rise_time = deadtime[0]
        else:
            rise_time = grad.rise_time
        if deadtime[1] > grad.fall_time:
            fall_time = deadtime[1]
        else:
            fall_time = grad.fall_time
        grad = pp.make_trapezoid(
            flat_area=area,
            flat_time=duration,
            rise_time=rise_time,
            fall_time=fall_time,
            system=system,
        )

    # Compute alignment between ADC and grad
    pivot = 0.5 - (1.0 - partial_fourier_factor)
    t_adc_to_center = dwell_time * (pivot * (num_samples - 1) + 0.5)
    if rampsamp:
        t_grad_to_center = pivot * pp.calc_duration(grad)
    else:
        t_grad_to_center = grad.rise_time + pivot * grad.flat_time
    adc_delay = t_grad_to_center - t_adc_to_center
    adc_delay = system.adc_raster_time * np.round(adc_delay / system.adc_raster_time)

    # Create ADC
    adc = pp.make_adc(
        num_samples=num_samples,
        dwell=dwell_time,
        delay=adc_delay,
        system=system,
    )

    # Set pieces
    if rstrip or lstrip:
        try:
            grad_rise, grad_flat, grad_fall = pp.split_gradient(grad, system)
        except Exception:
            grad_flat = None
            grad_rise, grad_fall = pp.split_gradient_at(grad, grad.rise_time, system)
    if lstrip:
        adc.delay -= grad.rise_time
    if lstrip and rstrip:
        if grad_flat is None:
            log_and_raise('Gradient is too short, cannot isolate a flat portion')
        grad = grad_flat
        grad.delay = 0.0
    elif lstrip:
        grad = pp.add_gradients([grad_flat, grad_fall], system=system)
        grad.delay = 0.0
    elif rstrip:
        grad = pp.add_gradients([grad_rise, grad_flat], system=system)

    return grad, adc
